version: '3'
services:
  ghost:
    image: ghost:latest
    container_name: ghost
    restart: always
    ports:
      - 2368:2368
    environment:
      - url=https://test.emlog.app
      - database__client=sqlite3
      - database__connection__filename=/var/lib/ghost/content/data/ghost.db
      - NODE_ENV=production
      - server__port=2368
      - server__host=0.0.0.0
      - server__socket=0.0.0.0:2368
      - server__trust_proxy=true
    volumes:
      - ghost-content:/var/lib/ghost/content
      - ghost-config:/var/lib/ghost/config
    networks:
      - ghost-network

volumes:
  ghost-content:
  ghost-config:

networks:
  ghost-network:
    driver: bridge